import XCTest
import AppKit
@testable import ClipboardKit

final class ClipboardPrivacyTests: XCTestCase {
    @MainActor
    func testSensitiveAndTransientCopiesAreExcluded() {
        for type in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"] {
            XCTAssertTrue(ClipboardMonitor.shouldIgnore(types: [.string, .init(type)]))
        }
        XCTAssertFalse(ClipboardMonitor.shouldIgnore(types: [.string]))
        XCTAssertFalse(ClipboardMonitor.shouldIgnore(types: [.png, .fileURL]))
    }

    @MainActor
    func testHostStorageAndImmediateClear() throws {
        let folder = "ClippyTests-\(UUID().uuidString)"
        ClipboardKitConfig.storageFolderName = folder
        let storage = ClipboardItem.storageDirectoryURL
        defer { try? FileManager.default.removeItem(at: storage) }
        XCTAssertEqual(storage.lastPathComponent, folder)
        let manager = ClipboardManager.shared
        manager.addItem(.fromText("test-only clipboard entry", source: "Unit test"))
        XCTAssertEqual(manager.items.count, 1)
        ClipboardKitConfig.maximumHistoryItems = { 2 }
        manager.addItem(.fromText("second test item", source: "Unit test"))
        manager.addItem(.fromText("third test item", source: "Unit test"))
        XCTAssertEqual(manager.items.count, 2)
        ClipboardKitConfig.maximumHistoryItems = { 1 }
        manager.enforceHistoryLimit()
        XCTAssertEqual(manager.items.count, 1)
        ClipboardKitConfig.maximumHistoryItems = { 400 }
        manager.clearHistory()
        XCTAssertTrue(manager.items.isEmpty)
        let data = try Data(contentsOf: storage.appendingPathComponent("history.json"))
        let stored = try JSONDecoder().decode([ClipboardItem].self, from: data)
        XCTAssertTrue(stored.isEmpty, "Clear must reach disk synchronously before the app terminates.")
        let usage = try Data(contentsOf: storage.appendingPathComponent("clipboard-usage.json"))
        let records = try XCTUnwrap(JSONSerialization.jsonObject(with: usage) as? [String: Any])
        XCTAssertTrue(records.isEmpty, "Clearing history must also erase copied text retained for suggestions.")

    }
}
