import Foundation
import AppKit
import Combine

/// Monitors the system clipboard for changes
@MainActor
public final class ClipboardMonitor: ObservableObject {
    public static let shared = ClipboardMonitor()

    /// Whether monitoring is active
    @Published public private(set) var isMonitoring = false

    /// Timer for polling the clipboard
    private var timer: Timer?

    /// Last known change count from the pasteboard
    private var lastChangeCount: Int = 0

    /// Reference to the clipboard manager
    private let clipboardManager: ClipboardManager

    /// Polling interval in seconds
    private let pollingInterval: TimeInterval = 0.5

    private static let vscodeResourceTypes = [
        "application/vnd.code.resources",
        "web application/vnd.code.resources",
    ]

    /// VS Code / Cursor desktop writes copied explorer files with this format.
    private static let codeFileListType = "code/file-list"

    private init() {
        self.clipboardManager = ClipboardManager.shared
        self.lastChangeCount = NSPasteboard.general.changeCount
    }

    /// Starts monitoring the clipboard
    public func startMonitoring() {
        guard !isMonitoring else { return }

        isMonitoring = true
        lastChangeCount = NSPasteboard.general.changeCount

        timer = Timer.scheduledTimer(withTimeInterval: pollingInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkClipboard()
            }
        }

        // Add to common run loop modes so it works during menu tracking
        if let timer = timer {
            RunLoop.current.add(timer, forMode: .common)
        }
    }

    /// Stops monitoring the clipboard
    public func stopMonitoring() {
        timer?.invalidate()
        timer = nil
        isMonitoring = false
    }

    /// Capture a copy that arrived just before a paste, before the next timer tick.
    func capturePendingCopy() {
        guard isMonitoring else { return }
        checkClipboard()
    }

    /// Checks the clipboard for changes
    private func checkClipboard() {
        let pasteboard = NSPasteboard.general
        let currentChangeCount = pasteboard.changeCount

        // Check if the clipboard has changed
        guard currentChangeCount != lastChangeCount else { return }
        lastChangeCount = currentChangeCount
        guard !Self.shouldIgnore(types: pasteboard.types ?? []) else { return }

        // Get the active application name
        let sourceApp = NSWorkspace.shared.frontmostApplication?.localizedName

        // Try to get content from the clipboard
        let items = extractClipboardContent(from: pasteboard, source: sourceApp)
        var copiedMediaIDs: [UUID] = []
        for item in items {
            clipboardManager.addItem(item)
            if item.isDraggableMedia, let saved = clipboardManager.items.first {
                copiedMediaIDs.append(saved.id)
            }
        }
        RecentMediaQueue.shared.recordPasteboardCopy(copiedMediaIDs, changeCount: currentChangeCount)
    }

    /// Respect the standard hints used by password managers and temporary copies.
    static func shouldIgnore(types: [NSPasteboard.PasteboardType]) -> Bool {
        let excluded: Set<String> = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
            "com.agilebits.onepassword",
        ]
        return types.contains { excluded.contains($0.rawValue) }
    }

    /// Extracts content from the pasteboard
    private func extractClipboardContent(from pasteboard: NSPasteboard, source: String?) -> [ClipboardItem] {
        if let fileItems = extractFileItems(from: pasteboard, source: source), !fileItems.isEmpty {
            return fileItems
        }

        // Check for images
        if let images = pasteboard.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
           let firstImage = images.first,
           let item = ClipboardItem.fromImage(firstImage, source: source) {
            return [item]
        }

        // Check for text (most common)
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            return [ClipboardItem.fromText(text, source: source)]
        }

        return []
    }

    private func extractFileItems(from pasteboard: NSPasteboard, source: String?) -> [ClipboardItem]? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [
            .urlReadingFileURLsOnly: true,
        ]

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL] {
            let fileURLs = urls.filter(\.isFileURL)
            if !fileURLs.isEmpty {
                return fileURLs.map { ClipboardItem.fromFileURL($0, source: source) }
            }
        }

        if let paths = pasteboard.propertyList(forType: NSPasteboard.PasteboardType("NSFilenamesPboardType")) as? [String] {
            let fileURLs = existingFileURLs(from: paths)
            if !fileURLs.isEmpty {
                return fileURLs.map { ClipboardItem.fromFileURL($0, source: source) }
            }
        }

        if let codeFileItems = extractCodeFileList(from: pasteboard, source: source), !codeFileItems.isEmpty {
            return codeFileItems
        }

        if let vscodeItems = extractVSCodeResources(from: pasteboard, source: source), !vscodeItems.isEmpty {
            return vscodeItems
        }

        if let uriListItems = extractURIListFiles(from: pasteboard, source: source), !uriListItems.isEmpty {
            return uriListItems
        }

        if let textPathItems = extractTextFilePaths(from: pasteboard, source: source), !textPathItems.isEmpty {
            return textPathItems
        }

        return nil
    }

    /// Cursor / VS Code desktop: newline-separated file URIs in `code/file-list`.
    private func extractCodeFileList(from pasteboard: NSPasteboard, source: String?) -> [ClipboardItem]? {
        let type = NSPasteboard.PasteboardType(Self.codeFileListType)
        guard let data = pasteboard.data(forType: type),
              let raw = String(data: data, encoding: .utf8) else {
            return nil
        }

        let urls = raw
            .split(whereSeparator: \.isNewline)
            .compactMap { line -> URL? in
                let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
                guard !trimmed.isEmpty, let url = URL(string: trimmed), url.isFileURL else { return nil }
                return FileManager.default.fileExists(atPath: url.path) ? url : nil
            }

        guard !urls.isEmpty else { return nil }
        return urls.map { ClipboardItem.fromFileURL($0, source: source) }
    }

    /// Cursor / VS Code store copied explorer files as JSON URIs on a custom pasteboard type.
    private func extractVSCodeResources(from pasteboard: NSPasteboard, source: String?) -> [ClipboardItem]? {
        for typeName in Self.vscodeResourceTypes {
            let type = NSPasteboard.PasteboardType(typeName)
            guard let data = pasteboard.data(forType: type) else { continue }

            if let urls = parseVSCodeResourceData(data), !urls.isEmpty {
                return urls.map { ClipboardItem.fromFileURL($0, source: source) }
            }
        }

        if let items = pasteboard.pasteboardItems {
            for item in items {
                for type in item.types where type.rawValue.contains("code.resources") {
                    guard let data = item.data(forType: type) else { continue }
                    if let urls = parseVSCodeResourceData(data), !urls.isEmpty {
                        return urls.map { ClipboardItem.fromFileURL($0, source: source) }
                    }
                }
            }
        }

        return nil
    }

    private func parseVSCodeResourceData(_ data: Data) -> [URL]? {
        guard let json = try? JSONSerialization.jsonObject(with: data) else { return nil }

        let resourceDicts: [[String: Any]]
        if let array = json as? [[String: Any]] {
            resourceDicts = array
        } else if let dict = json as? [String: Any] {
            resourceDicts = [dict]
        } else {
            return nil
        }

        let urls = resourceDicts.compactMap { parseVSCodeResource($0) }
        return urls.isEmpty ? nil : urls
    }

    private func parseVSCodeResource(_ dict: [String: Any]) -> URL? {
        if let scheme = dict["scheme"] as? String,
           let path = dict["path"] as? String,
           scheme == "file" {
            let url = URL(fileURLWithPath: path)
            return FileManager.default.fileExists(atPath: url.path) ? url : nil
        }

        if let external = dict["external"] as? String,
           let url = URL(string: external),
           url.isFileURL,
           FileManager.default.fileExists(atPath: url.path) {
            return url
        }

        return nil
    }

    private func extractURIListFiles(from pasteboard: NSPasteboard, source: String?) -> [ClipboardItem]? {
        let uriListType = NSPasteboard.PasteboardType("public.utf8-plain-text")
        let candidates = [
            pasteboard.string(forType: NSPasteboard.PasteboardType("public.url")),
            pasteboard.string(forType: NSPasteboard.PasteboardType("text/uri-list")),
            pasteboard.string(forType: uriListType),
        ]

        for candidate in candidates {
            guard let text = candidate else { continue }
            let lines = text
                .split(whereSeparator: \.isNewline)
                .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
                .filter { !$0.isEmpty && !$0.hasPrefix("#") }

            let urls = lines.compactMap { line -> URL? in
                guard line.hasPrefix("file://"), let url = URL(string: line), url.isFileURL else { return nil }
                return FileManager.default.fileExists(atPath: url.path) ? url : nil
            }

            if !urls.isEmpty {
                return urls.map { ClipboardItem.fromFileURL($0, source: source) }
            }
        }

        return nil
    }

    private func extractTextFilePaths(from pasteboard: NSPasteboard, source: String?) -> [ClipboardItem]? {
        guard let text = pasteboard.string(forType: .string) else { return nil }

        let lines = text
            .split(whereSeparator: \.isNewline)
            .map { String($0).trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }

        if lines.count == 1, let url = EditorWorkspaceResolver.resolveFileURL(from: lines[0], sourceApp: source) {
            return [ClipboardItem.fromFileURL(url, source: source)]
        }

        if lines.count > 1 {
            let urls = lines.compactMap { EditorWorkspaceResolver.resolveFileURL(from: $0, sourceApp: source) }
            if urls.count == lines.count, !urls.isEmpty {
                return urls.map { ClipboardItem.fromFileURL($0, source: source) }
            }
        }

        return nil
    }

    private func existingFileURLs(from paths: [String]) -> [URL] {
        paths.compactMap { path in
            let url = URL(fileURLWithPath: path)
            var isDirectory: ObjCBool = false
            guard FileManager.default.fileExists(atPath: url.path, isDirectory: &isDirectory),
                  !isDirectory.boolValue else {
                return nil
            }
            return url
        }
    }

    /// Temporarily pauses monitoring (useful when we're about to copy something ourselves)
    public func pauseMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    /// Resumes monitoring after a pause
    public func resumeMonitoring() {
        guard isMonitoring else { return }

        // Update change count to ignore our own paste
        lastChangeCount = NSPasteboard.general.changeCount

        timer = Timer.scheduledTimer(withTimeInterval: pollingInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkClipboard()
            }
        }

        if let timer = timer {
            RunLoop.current.add(timer, forMode: .common)
        }
    }
}
